server:
  port: ${PORT:5000}
  profiles:
    active: default
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
    view-names: thymeleaf/*
    check-template-location: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://seczym1n7yr4unha:ves3pu1e3joha3vp@kfgk8u2ogtoylkq9.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/ce61jybf2zm066aa
    username: seczym1n7yr4unha
    password: ves3pu1e3joha3vp
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true



  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false