server:
  port: ${PORT:5000}
  profiles:
    active: default
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
    view-names: thymeleaf/*
    check-template-location: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://vhgkvo8rzwitlu28:ofjy524wp2dai209@ik1eybdutgxsm0lo.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/t98532cpmd1ifgj0
    username: vhgkvo8rzwitlu28
    password: ofjy524wp2dai209

#    url: jdbc:mysql://localhost:3306/busking?serverTimezone=Asia/Seoul
#    username: emibgo
#    password: wlgns2
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
    hikari:
      maximum-pool-size: 9
  main:
    allow-bean-definition-overriding: true




  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: false
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
